apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Laura-Legat/cloudnative.git
    targetRevision: HEAD 
#track myapps folder in github repo
    path: notejs-src
  destination:
    server: https://kubernetes.default.svc
    namespace: notejs

# configure that namespace notejs is created automatically if not already there
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

# automatically sync changes in github repo
# the automated attribute forces argocd to pull from the github repo every 3 mins

    automated:
# override any changes made manually to the cluster with the declarations in the github repo
# make github repo single point of truth
      selfHeal: true
# if we delete a file, we configure argocd to do the same
      prune: true

