apiVersion: v1
kind: Service
metadata:
  name: notejs-service
spec:
# export all pods with label notejs
  selector:
    app: notejs
  ports:
# listen for requests on port 80 and forward them to port 3000 of the target pods
    - name: notejs-service-port
      protocol: TCP
      port: 80
      targetPort: 3000
# make  pods accessible from outside of the cluster
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notejs-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notejs-service
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejs-deployment
# later used to bind the service to the pod
  labels:
    app: notejs
spec:
# spin up 2 replicas of my notejs pod (containing the containers)
  replicas: 1
# select pods with app:notejs label
  selector:
    matchLabels:
      app: notejs
  template:
    metadata:
# define label for the pods wrapping up a notejs container
      labels:
        app: notejs
    spec:
      containers:
      - name: notejs
        image: lauralgt/notejs:1.0.0
        ports:
        - containerPort: 3000
# the following info will be made available to the process in the container
        env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/thoughts
# forces the Docker image to always be re-downloaded, even if already downloaded
        imagePullPolicy: Always
# pass secret stored for private image repo
      imagePullSecrets:
      - name: regcred