apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAkOztwvugT61M1jk8G0FNdj17EPOAXZ703d56sEdKHarPcgLYORJ2QE/nPa26pwJXeu6HNF+yPf/FrlSwiLT/EJULaqUzvX2aKbtxT1hiKakM5m1u9h1OtZyuXvkuYHbJNnUmrUTY7mWnfC2/5YmEfmI4UinnZXOVUZd9JO0FXriwQC8fmnvs/ecUw3Wr3dcaacQLXEXreO79uziCjnayRZWRnD8NxhT/tcKZ3OJXrLnC9dlYf+gnDXQr5Z4Jv35rfMpE707opsFURG+tx/WpOMZoSslF+5nAwa57Gz3PiYrzCosoAYtcvc9L15fhWmvvPHLzZYB3VL+HOGgKVXsvzMCofDJ2uYzDZJMJegsEkKLpZnJ88/xEA1htDyxo5hPQwmj41nD9cjZu7qEQsv/S1bjAwMMq4UDumY4K0qX92oCb8a/O1oV3V3zVrrDao/ee7TZlg6oHZZboXUF1IBwm4e1nHURVrWvF/0Qoo8EEjUKjZn3rJUYYzq5y3a7wNyzP6+7CdZWx6K5Qzay/3ObgCFbXBCJjcCuTCMTcLzEq9VdxLQ5kHSqEVZzuf6LAit/g0IMCiVLzWNBWxI+Pq64fxZ7MDs+qumxEdFuDK+yH07yXZJx2BudpABUErbOQGJ5FR06pP8WF1eWTIunZbxqoB69Q5L6DZwBRFmMmmsly27aRXe643ibCKiP37MX4+x2s7WthDETscS2T8WlVEB+9HYCzsDhp7frJ1+q0UjvbOO/lXa0ci7buDKu5QQ+6+yG29VW0vi3gQ8fkemXHXgY4qg8gNl9omvF1hmmHwS5DO1/qngQU5XTma73jq9RkGJQiNoV7pnNDSD3RQQn9fbIIzJ7fuRIinWz1WozWYdyxqTn/amYhi0QVMkfzMVGXMVd7VIKzZKShgd0ptSuyE71DA349Lkaar8InG3g==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson

