apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: myfirstapp
spec:
  encryptedData:
    .dockerconfigjson: AgB+s8TatBtVghcXAa4QzNe1+zt06zFKLghKCvDf3fqGWubrLEcHtz3uZhteyk6fT2EW+WxwcWpx/1f1CtItgX6GYR4DENzBMvjPUd7I+RkjgBlYPpEgtRXzySCrJbrb/QKkedx1X2XQwtjw7K4r5XBsu0WWvtJQ4Q9pQwyT3nN31glyvJBoAtYLUMQ2UCPkx5zVFL9XyimrzM10hMNJ4QtiU+6zBMczETlYZvGZI9h8zKKSrPBjHA6RAihNdWetF6dQrzs4cnwpL8twyMQV8q29GQMoQWC91+vKXH2TXgzbmjzMoJpeySGGS3vW0X1fKECrWo65vVRY7jMr2C/01u7SB1X3OeF2cWMz6sGvlqW1CH4Ns5YvSyPr/I4uY1DctvdW9Fvu+vj77JV/7LAGBKbaJe9ffSFwMeDOcNMQMz2da2MKnxjo6KPnYfxemM8SJJzdbdBSnnK4HWr+GYJPdbk1Bu26/IyzwNma0wqsEogS6pVzkzL4sxEAEacO7DbC9LL6nB/TzVyfdmDYXW/Wsjf8GNxnq8cPBDWTHjuiJN6XjsLMHm563rLCAvLvSuIz3To4KbiRmkOKHvLppi87CLdAjV+xTr64gvVB2HbBIqXV+KRePdL9jZuHV7z4dMNpcpWxGswToiZufIYruhQIT91wTtxJ7flaFip5iS3FoR8VmWiLMaNSkPHHUb/BoYP/ZDjKAp9M/3g4nT7nbTkPw17USa0dkRt0UeEMiTbU8zUqlTAkOktdbA9ukLdpH5f/NgjFeOh8Nr3K6r9VwGvCsWG90U4dAol4qWxKJZoat7LnTtDK99Bw8A/8v0P0kZonJFbniRaaV2PWcUxNnGB/pn545Y2OHcih4+tSb9m82uxaB6htOf83abFWky8TVYdlSNZWcu0wc7Xc+CEta/7J03VSZFacgUUTghGWkQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: myfirstapp
    type: kubernetes.io/dockerconfigjson

