apiVersion: v1
kind: Service
metadata:
  name: notejs-prod-service
  namespace: production
spec:
# export all pods with label notejs
  selector:
    app: notejs-production
  ports:
# listen for requests on port 80 and forward them to port 3000 of the target pods
    - name: notejs-prod-service-port
      protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notejs-prod-ingress
  namespace: production
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
# all http calls with /prod prefix are forwarded to notejs-service:80
            name: notejs-prod-service
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejs-prod-deployment
  namespace: production
# later used to bind the service to the pod
  labels:
    app: notejs-production
spec:
# spin up 2 replicas of my notejs pod (containing the containers)
  replicas: 1
# select pods with app:notejs-production label
  selector:
    matchLabels:
      app: notejs-production
  template:
    metadata:
# define label for the pods wrapping up a notejs container
      labels:
        app: notejs-production
    spec:
      containers:
      - name: notejs-production
        image: lauralgt/notejs:3.0.0
        ports:
        - containerPort: 3000
# the following info will be made available to the process in the container
        env:
        - name: MONGO_URL
# connect to notes collection
          value: mongodb://mongo:27017/notes
        - name: PORT
          value: "3000"
        - name: ROUTER_BASE
          value: /prod
# forces the Docker image to always be re-downloaded, even if already downloaded
        imagePullPolicy: Always
# pass secret stored for private image repo
      imagePullSecrets:
      - name: regcred-production