apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgBJh8oXTRhOgu47kXHK0bhxtptPc8TaelaGH1lHvr9oYXVAi6SmIouJf4/213ssJQqlAQVo/XyJbIOhnWH/PxMJ95VSPLU+VdZg5CExdy3xKUWCOflaFHkwnJSeGpEqSI8+6LqXayf5QpfTchLGwhqKAtg38qWeN9jza0pghcP3yW+hfL0YIqr6O17Ui3a3bXDjORCRqvDUKNZKpzGSPWjF69IIdJ1CK4qofgnTYfRYf1vXhEOzb0BeqS6JfvBh5Wij0Kl4Sil249iFZ0AiUnxssH8eTZUsjdnZVFAdJBoA4nXDQJ/SHZM54Rr6GLcyqgwjFsmbTNyfaMjCkr46lUlAHz/gDx+qrOhZu2ymYl351mW5tYBikAAkn+BRyC/L6pokFIlu53SgEryO9kCtbanqVvyqxHs8v/4+jGi1mpIUmUweM3lk9UegxXuYGpvLgpL7vzDjKw5SwLgWHIyFJ35thdSwV32f3MJywL82PhLp4citg9jG0cRyH6uZ+/D0Ti+ODI3fW4sOuOQCCgM69N/Ykz+P3kMlJyU7s0OcxhZZe4jku6yOLRPzHZLnFtKk8YOfKOMs15rvGnSveBa/f3EdwBqApzD+KN/XWPH5rA7TaAtwY8IjVDToDQSH00A2k/jKk4lW9XfRjYQL/28Uyn+2uHcAacpr+BSWgm/2pd/eYdSn+84t9kTaeS8Qb0v0C0ZS70FstZJIYs+BEq6wdD0JHrQOjpsJQvQlheogaoFLjMAtD208wAcxtVGyJBis10u5V788FqgsMEkTtewi+b1uxnEjTW8UncMVe21LZZLBTyzyjBVOBkXgIW1aBVzePxegzA2kMqV8ND5qV+9Gm33diV+o3sFnNhtn8MPoJn6n/tIUkaddBc6nw7lrEK969I5dATMHrdfKBAPQa1c30DPiz6ogMXWR3LBZMQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: production
    type: kubernetes.io/dockerconfigjson

